### ISSUE TITLE
Binary format

### ISSUE THREAD

**Issue by jerzakm** [nickbabcock/jomini#101]
Do you plan to maybe add bindings for parsing binary files? Autosaves for some (all?) games are forced into binary format and it'd be very convenient to not have to manually use the rust lib.

**Comment by nickbabcock** [comment]
Do you have an API example in mind of how the binary format would be represented and used if exposed?

**Comment by jerzakm** [comment]
What if it was similar to the existing `parseText`? 

```js
import { Jomini } from "jomini";
const data = // binary data, read from autosave.v3 for example
const parser = await Jomini.initialize();
```

**variant 1 - everything happens in 1 step. Binary to js object**
```js
const out = parser.parseBinary(data);
```

**variant 2 - 2 steps. First binary to text, then text to js object**

```js
const text = parser.parseBinary(data);
//or
const text = parser.binaryToText(data);

const out = parser.parseText(data);
```

I'm not super familiar with Rust and wasm binding gotchas when it comes to this stuff, so please don't spend too much time on something like this on my account :) If it requires more than adding simple bindings then maybe this is the excuse I needed to finally dip more into rust-world.

**Comment by nickbabcock** [comment]
The biggest hurdle is that many keys of binary objects are numbers. The number->string key mapping changes per game and per patch and paradox said no last time I asked if I could release this map. So in order to implement melting, the api would need to accept a user supplied map, which seems like a pretty big hurdle. So I've been wary of adding it with a big caveat

**Comment by jerzakm** [comment]
I wasn't aware of the binary mapping issue, thanks for explaining. I think I'll just hack in `rakaly-cli` and call it good enough for now.

**Comment by nickbabcock** [comment]
Sounds good, let me know if there's more I can do to assist.
