### ISSUE TITLE
Lots of results are 4294967295 "32-bit unsigned integer" when reading Stellaris saves. 

### ISSUE THREAD

**Issue by jamessimo** [nickbabcock/jomini#117]
I am not sure how or what is causing this. but I am trying to get information about starbases and lots of them are just 
```
starbases={
    4294967295 
}
```

and I mean a lot, a ctrl+F for that number returns 19999+ results. 

pretty sure this is a strange issue with some way I am getting the data or the jomini parser does this. 
https://en.wikipedia.org/wiki/4,294,967,295

I am getting the save data as json like this; 

```js
document.getElementById('fileInput')!.addEventListener('change', async (event) => {
  const input = event.target as HTMLInputElement;
  if (input.files && input.files[0]) {
    const file = input.files[0];
    const reader = new FileReader();
    reader.readAsText(file, "windows1252");
    reader.onload = async (evt) => {
      try {
        const loadedMapName = file.name;
        const zipReader = new ZipReader(new BlobReader(file));
        const entries = await zipReader.getEntries();
        if (entries.length) {
          let text = '';
          if (entries[0]) {
            //@ts-ignore
            text = await entries[0].getData(new TextWriter());
          }
          console.log('Extracted Text:', text); // Log the extracted text for inspection

          // Check the length and a snippet of the content
          console.log('Extracted Text Length:', text.length);
          console.log('Extracted Text Snippet:', text.substring(0, 200));

          const parsedData = await saveParser.parseText(text, { encoding: "windows1252" }, (q) => q.json());
          const save = JSON.parse(parsedData);

          console.log("Parsed Data:", save);
          drawSystems(save.galactic_object);
          //drawHyperlanes(save.galactic_object);

          await zipReader.close();

        }
      } catch (error) {
        console.error("Error parsing file:", error);
      }
    };
  }
});
```

I wanted to provide the code as this could be the unzipping method I use to get this to work on the web browser without a nodejs server. 

If you need my game save, you can find it here with my full code. 
https://github.com/jamessimo/stellaBabylon/blob/main/src/ironman.sav

**Comment by nickbabcock** [comment]
Thanks for the savefile! What is the bug? I unzipped the savefile and saw that `4294967295` occurs 20145 times in the gamestate

**Comment by jamessimo** [comment]
> Thanks for the savefile! What is the bug? I unzipped the savefile and saw that `4294967295` occurs 20145 times in the gamestate

The bug is it's not supposed to be that I think. I tested with another parser and got the same issue.
https://github.com/PyPDX/stellaris-save-vid

Im trying to work out how to get "Ownership" or "who controls what systems" and I think its dictated by the starbase but I can't get any good information off the starbases.

**Comment by nickbabcock** [comment]
sounds like a bug in stellaris or your mental model, no?

jomini simply exposes the value contained within the save

**Comment by jamessimo** [comment]
> sounds like a bug in stellaris or your mental model, no?
> 
> jomini simply exposes the value contained within the save

there is a chance my mental model is off. 4294967295 could also be a NIL value, I will investigate more but right now I am having issues working out border sizes and ownership.

**Comment by jamessimo** [comment]
I’ll close this, the int is just a Nil value. I was confused why my save had so many but realized that I had 2 saves of the same name and the one I was looking at was a fresh game so lots of Nil values.
