### ISSUE TITLE
Rip out json3 dependency - deprecated and unmaintained

### ISSUE THREAD

**Issue by soryy708** [nickbabcock/jomini#14]
[`package.json`](https://github.com/nickbabcock/jomini/blob/master/package.json#L22) shows that this project has [json3](https://www.npmjs.com/package/json3) as a dependency. 

From it's npm page:
> JSON 3 is **deprecated** and **no longer maintained**. Please don't use it in new projects, and migrate existing projects to use the native `JSON.parse` and `JSON.stringify` instead.

**Comment by nickbabcock** [comment]
Good call. Either a pull request is fine or I will take care of it when I'm back from holiday in a week
