### ISSUE TITLE
Set up linter rules

### ISSUE THREAD

**Issue by soryy708** [nickbabcock/jomini#24]
[ESLint](https://eslint.org/) is a JavaScript linter.
A linter is a white-box testing utility which runs static analysis on your code, and points out potential issues with style, code smells, and potential bugs.

ESLint is configured via `.eslintrc` file. I can set one up, but code standards & style guides need to be established first.

**Comment by nickbabcock** [comment]
I assume the following would be a reasonable start.

```json
{
  "extends": ["eslint:recommended", "plugin:node/recommended", "prettier"]
}
```

Probably tucked inside `eslintConfig` field in a package.json so we don't need to clutter the root directory any more than it needs to be.

Maybe there is some way we can have this config without needing to add eslint-config-prettier, eslint-plugin-node, eslint and to the package.json (and package-lock.json). I'd rather just have the latest version of those dependencies ran every time I wanted to lint instead of some pinned version.

**Comment by soryy708** [comment]
Extending the recommended is reasonable, but it doesn't cover many very useful checks. Also, the "recommended" may be working on a style that's different from the existing convention here.

To set up the latest version instead of some pinned version, just use the `>={version}` rule in package.json instead of `={version}`

The linter configuration can be quite long, especially if you add a lot of plugins.
From what I've seen so far, looks like the common practice is to put it in its own file (`.eslintrc`) as opposed to in `package.json`.

Why do you care about cluttering the root directory? You can https://github.com/nickbabcock/jomini/issues/26 if you're concerned about what happens when the package is `npm install`ed.

**Comment by soryy708** [comment]
If we go with eslint, we'll obviously have to use `eslint` configuration.

I'm reading the docs for [eslint-plugin-node](https://www.npmjs.com/package/eslint-plugin-node) and it looks like a lot of these rules are already covered by the basic eslint. Which rules in particular do you want?

I'm reading the docs for [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier) and it looks like a lot of rules are also already covered by the basic eslint, and some may conflict. Which rules in particular do you want?

**Comment by soryy708** [comment]
I've implemented an .eslintrc (see pull request).
Here are a few issues I'd like to bring up for discussion:

* Which `ecmaVersion` are we targeting? Is this supposed to be run in a browser? or in a node environment? How far back to we provide backwards compatibility?
* `no-prototype-builtins` is part of `eslint:recommended`, but turning it on flags existing code as an error (specifically various calls to `.hasOwnProperty()`). Do we want to keep the rule off? or do we turn the rule on and fix the existing code?
* There are various instances of using `==` in the existing code when `===` could have been used. There's an option to turn on a rule to enforce that (`eqeqeq`).
* Do we care about magic numbers in the existing code? (`no-magic-numbers`)
* `var` declarations imply hoisting. There's a rule that enforces putting them on the top of the scope, so that the implied hoisting is communicated. (`vars-on-top`)
* `var` can be replaced with `const` or `let` in newer versions of JS. Do we want to enforce that? (`no-var`)
* Arrow callbacks are more concise and intuitive in terms of scope (e.g. `this` keyword semantics). Do we want to replace `function(){}`s with `()=>{}`s where possible? (`prefer-arrow-callback`)

**Comment by nickbabcock** [comment]
I'm happy to accept PRs that updates code to conform to some eslint rule, but as of now I have yet to see a solution that minimizes the amount of cruft that is added to the project. Any solution would need to be less than a half dozen lines.
