### ISSUE TITLE
Set up `files` field in package.json

### ISSUE THREAD

**Issue by soryy708** [nickbabcock/jomini#26]
Documentation: https://docs.npmjs.com/files/package.json#files

This will allow us to "go crazy" with extra files to support our workflow without cluttering the actual package.
For example, there isn't much reason to install the [`test/`](https://github.com/nickbabcock/jomini/tree/master/test) folder.

**Comment by nickbabcock** [comment]
Yeah this sounds ok

**Comment by soryy708** [comment]
This would make [`.npmignore`](https://github.com/nickbabcock/jomini/blob/master/.npmignore) redundant and okay to delete.

Speaking of, why is it there in the first place? `coverage/` is already in `.gitignore` and according to the [npm docs](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package):

> If there’s no .npmignore file, but there is a .gitignore file, then npm will ignore the stuff matched by the .gitignore file.

**Comment by nickbabcock** [comment]
Yes, looks like npmignore can be removed.

**Comment by nickbabcock** [comment]
Thank you for the suggestion, the `files` property is now specified in the latest release.
