### ISSUE TITLE
Document somewhere that jomini is supposed to run in node and in browser

### ISSUE THREAD

**Issue by soryy708** [nickbabcock/jomini#29]
Following the remark at https://github.com/nickbabcock/jomini/pull/27#issuecomment-573319591 :

> jomini can be used without issue in browsers with a bundler.

This should be clearly documented (perhaps in the README.md?), and appropriate instructions for  how to achieve it should be added to the documentation.

**Comment by nickbabcock** [comment]
Thank you for the suggestion, the readme now lists that the package can be used on node and in the browser.
