### ISSUE TITLE
Empty objects not handled

### ISSUE THREAD

**Issue by Genubath** [nickbabcock/jomini#36]
Empty objects seen in savefiles like
`2626653={ }`
throw `Expecting 'IDENTIFIER', '=', 'QIDENTIFIER', 'NUMBER', 'DATE', '{', 'BOOL', 'hsv', 'rgb', 'QDATE', got '}'`

**Comment by nickbabcock** [comment]
This has been released as part of v0.2.12. Thank you for reporting this issue.
