### ISSUE TITLE
File Isn't Parsed Correctly

### ISSUE THREAD

**Issue by dann2g** [nickbabcock/jomini#41]
I'm attempting to parse EU4 event files using Jomini but somewhere along the line something is going wrong.

With [RandomEvents.txt](https://gist.github.com/dann2g/65282fddadcb25da0082872bc078f8d4), for example, only data after the first province_event is parsed. After removing all instances of province_event, it seems only objects after the namespace declaration are parsed.

Is this a bug or am I doing something wrong?

(P.S. thanks so much for this project, it's amazing! Last time I parsed these files (without Jomini) it was a complete headache)

**Comment by nickbabcock** [comment]
Thanks for the report. I'm having a hard time replicating the issue. You can run what I'm trying here: https://repl.it/repls/HurtfulPrestigiousNumerator

I'm seeing all 4 ids printed

```js
[
  'random_event.21',
  'random_event.22',
  'random_event.23',
  'random_event.24'
]
```

Let me know if I missed something.

Code copied below for posterity:

```js
const { readFileSync } = require("fs");
const { Jomini } = require("jomini");

const buffer = readFileSync("./RandomEvents.txt");

(async function () {
  const parser = await Jomini.initialize();
  const data = parser.parseText(buffer, { encoding: "windows1252" });
  const provinceEvents = data['province_event'];
  const ids = provinceEvents.map((x) => x.id);
  console.log(ids);
})();
```

**Comment by dann2g** [comment]
Thanks for looking into this.

The issue is everything before the first `province_event` declaration is missing. If you search for `country_event` IDs, you'll see that only IDs from `random_event.25` onwards are there.

**Comment by nickbabcock** [comment]
Good spot, such a silly mistake. I'll have a fix within 24 hours

**Comment by nickbabcock** [comment]
This has been released, let me know if it is fixed!

**Comment by dann2g** [comment]
Seems to work now. Brilliant. Thanks so much for fixing this!
