### ISSUE TITLE
Question: Does the JSON pointer like strings support wildcards

### ISSUE THREAD

**Issue by davout1806** [nickbabcock/jomini#52]
Does the JSON pointer like strings feature you provide support wildcards? Such as

```
const prestiges = query.at('/countries/*/prestige');
```

Thanks

**Comment by nickbabcock** [comment]
No the JSON pointer feature set is limited at this time, though you can get what you want with advanced JSON parsers. This shows how to get all the prestige fields with oboe.js

```js
  const out = parser.parseText(
    buffer,
    { encoding: "windows1252" },
    (query) => query.json(),
  );

  const strm = Readable.from([out]);
  oboe(strm).node("countries.*.prestige", (prestige) => {
    console.log(prestige);
  });
```

**Comment by davout1806** [comment]
Thanks I'll take a look.
