### ISSUE TITLE
Bug? Parsing map/area.txt

### ISSUE THREAD

**Issue by davout1806** [nickbabcock/jomini#53]
While trying to parse map/area.txt file (using json layer) I noticed odd results if the area has color attribute.

Sample of map/area.txt
```
brittany_area = { #5
	color = { 118  99  151 }

	169 170 171 172 4384
}

normandy_area = { #4
	167 168 1879 4385
}
```
The results received:
```
{
      "brittany_area": { "color": [118, 99, 151], "169": 170, "171": 172, "4384": null },
      "normandy_area": [167, 168, 1879, 4385]
}
```
normandy_area seems OK. brittany_area is off. The code is interpreting the odd ids as object properties.

Not sure what the correct format should be since "brittany_area": { "color": [118, 99, 151], [169, 170, 171, 172, 4384] } would be invalid. You would have to add your own property name.

Is it possible currently to tell Jomini to ignore pieces **before** it parses?

Thanks

**Comment by nickbabcock** [comment]
Thanks for bringing this issue up. I've worked around it in my own code by detecting if an area is an object, and if it is, skip the color field and and take the rest as if they were a number array. Let me know if you want me to elaborate on this technique.

I believe the long term solution is to expose this phenomenon (of which I unofficially call "object trailers") as an additional property (called something like `trailer`), so the above would represented as:

```json
{
      "brittany_area": {
        "color": [118, 99, 151],
        "trailer": [169, 170, 171, 172, 4384 ]
      },
      "normandy_area": [167, 168, 1879, 4385]
}
```

So you'll still need to do object / array detection, but at least it's no longer too weird 😅 

Let me know if this sounds like a decent solution.

**Comment by davout1806** [comment]
Thanks for the info. Right now since I don't care about the color, I'm just doing regex replace color line with empty string before I pass the text to Jomini. But your solution is probably more flexible i.e. a mod has multiline color or something weird.

Your long term solution sounds reasonable to me.
