### ISSUE TITLE
Is this repo able to return timeline data?

### ISSUE THREAD

**Issue by agforero** [nickbabcock/jomini#57]
Title. I haven't found an issue with the project itself, I'm just inquiring to see if I could use this to pull each day within an EU4 timeline as JSON data. Would be useful for a project I'd like to work on.

**Comment by nickbabcock** [comment]
Absolutely! The history section of countries and provinces are easily exposed and one can create a timeline from this.

**Comment by agforero** [comment]
Awesome, so I could use that data to feed into something like Python?

**Comment by nickbabcock** [comment]
Yes, you could have two steps:

1. Use js to parse the data and massage it into a format that is easier to work with. Save this to a file.
2. Ingest this file with python

There are ways to directly use python without the intermediate JS step but it is a bit more complicated

**Comment by agforero** [comment]
Dope, thanks for your help.
