### ISSUE TITLE
How can I make this work with typescript and webpack

### ISSUE THREAD

**Issue by omermecitoglu** [nickbabcock/jomini#81]
Hi

Assuming it's possible after reading your blog post [here](https://nickb.dev/blog/recommendations-when-publishing-a-wasm-library/)

After tweaking my configs as you pointed there, I can build it without an error now, but it says **"fetch is not defined"** when i try to initialize it in an electron app.

tsconfig.json

```{
  "compilerOptions": {
    "outDir": "./build/",
    "noImplicitAny": true,
    "sourceMap": true,
    "module": "commonjs",
    "target": "es5",
    "jsx": "react",
    "allowJs": true,
    "baseUrl": ".",
    "paths": {
      "~*": ["src*"],
    },
    "moduleResolution": "node",
    "strictNullChecks": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true
  }
}
```
webpack.config.js
```
{
  name: "main",
  entry: "./src/main.ts",
  target: "electron-main",
  output: {
    path: path.resolve(__dirname, "build"),
    filename: "main.js",
  },
  plugins: [],
  module: {
    rules: [
      {
        test: /\.(ts|tsx)$/,
        loader: "ts-loader",
      },
      {
        enforce: "pre",
        test: /\.js$/,
        loader: "source-map-loader",
      },
      {
        test: /\.wasm/,
        type: 'asset/resource'
      },
    ],
  },
  resolve: {
    extensions: [".ts", ".tsx"],
  },
}
```

Can you tell me what am i doing wrong?

**Comment by omermecitoglu** [comment]
Also trying to switch to slim version, but it says:

`Cannot find module 'jomini/slim' or its corresponding type declarations.`

changed "moduleResolution" to "node16" in tsconfig.json, now it says:

`Module 'jomini/slim' cannot be imported using this construct. The specifier only resolves to an ES module, which cannot be imported synchronously. Use dynamic import instead.`

**Comment by omermecitoglu** [comment]
I just found a workaround.

Using webpack copy plugin to provide the wasm file to my build directory and then using `await Jomini.initialize()` without `{ wasm }` because this is trying to fetch it from a url. I can understand your reason, webpack should be used only for web, but sometimes things get dirty and you may want to use webpack in backend too :disappointed_relieved:

**Comment by nickbabcock** [comment]
> using `await Jomini.initialize()` without `{ wasm }` because this is trying to fetch it from a url.

I can probably take an in depth look at this use case later, but as you've seen, if one passes a string to `initialize`, it will assume it is a URL and fetch it. A potential solution would be to [instantiate the Wasm yourself](https://nodejs.dev/learn/nodejs-with-webassembly#how-to-use-it) from the string returned from a webpack `asset/resource`  and pass the result as the `wasm` parameter.

**Comment by omermecitoglu** [comment]
> I can probably take an in depth look at this use case later, but as you've seen, if one passes a string to `initialize`, it will assume it is a URL and fetch it. A potential solution would be to [instantiate the Wasm yourself](https://nodejs.dev/learn/nodejs-with-webassembly#how-to-use-it) from the string returned from a webpack `asset/resource` and pass the result as the `wasm` parameter.

```
const _wasm = await readFile(path.resolve(__dirname, wasm));
const parser = await Jomini.initialize({ wasm: _wasm });
```
This worked. I didn't pay enough attention to the source code, used raw-loader in webpack, it didn't work either and I didn't try something similar again. Thanks for your answer.

**Comment by nickbabcock** [comment]
Since the workaround is good enough, I'm going to close this issue, but I may revisit in the future to inline the node js code for the electron use case.
