### ISSUE TITLE
Can not handle > and <

### ISSUE THREAD

**Issue by Ax72864** [nickbabcock/jomini#9]
some stellaris files  in current version 2.3.1(such as "common/technology/00_synthetic_dawn_tech.txt") contains '>' , '<' , '>=' and '<=' operators will cause parse error. 

`research_leader = {`
	`area = engineering`
	`has_trait = "leader_trait_expertise_industry"`
	`has_level > 2`
`}`

It is a conditional statements that maybe can convert to 'GREATER_THAN'"SMALLER_THAN"  in json.

`"research_leader": {`
	`"area": "engineering",`
	`"has_trait": "leader_trait_expertise_industry",`
	`"GREATER_THAN": {`
		`"has_level" : 2`
	`}`
`}`

**Comment by nickbabcock** [comment]
Hmm I would lean to having it be nested like so

```
has_level: {
  GREATER_THAN: 2
}
```

**Comment by Ax72864** [comment]
You are right,thanks.😄

**Comment by nickbabcock** [comment]
Released in v0.2.9
