### ISSUE TITLE
Strings containing numbers become numbers

### ISSUE THREAD

**Issue by Clashsoft** [nickbabcock/jomini#98]
This part of a Stellaris custom empire file:

```
		name={
			full_names={
				key="01"
			}
		}
```

Is parsed as:

```
      "name": {
        "full_names": {
          "key": 1
        }
      },
```

This is problematic, because it makes it hard to round-trip convert the JSON back to text.
Especially because the leading 0 is dropped.

I propose parsing quoted numbers as strings and not numbers.

**Comment by nickbabcock** [comment]
I think this is a good idea. Let me see what I can do
